// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9J4gbpk0QWl7fp9LMnwY3gtwJoBNA7lQ',
    appId: '1:651856058825:web:f740634a43f0e6c1b63018',
    messagingSenderId: '651856058825',
    projectId: 'wekala-9189f',
    authDomain: 'wekala-9189f.firebaseapp.com',
    storageBucket: 'wekala-9189f.firebasestorage.app',
    measurementId: 'G-ZZZ2Y5SPG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAne474KbTww_03AJj-445nr0yQGOsxUk',
    appId: '1:651856058825:android:3c266295f2cc9a0ab63018',
    messagingSenderId: '651856058825',
    projectId: 'wekala-9189f',
    storageBucket: 'wekala-9189f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmv2mrDhLCzRsK7HuXysB5Ad5SoO2UkBM',
    appId: '1:651856058825:ios:008925cdece992cfb63018',
    messagingSenderId: '651856058825',
    projectId: 'wekala-9189f',
    storageBucket: 'wekala-9189f.firebasestorage.app',
    iosBundleId: 'com.wekala.user',
  );
}
